FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

RUN apt update && \
    DEBIAN_FRONTEND="noninteractive" apt install -y --no-install-recommends \
    python3 python3-dev python3-pip make cmake ninja-build gcc g++ libgl1-mesa-dev libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html

# TODO: Load Detectron2 weights

WORKDIR /app

VOLUME /app/data
VOLUME /app/Video2mesh

ENTRYPOINT ["python3"]