FROM anthonydickson/hive:runtime-cu118

ENV BUNDLE_FUSION_PATH=/bundle_fusion
ENV BUNDLE_FUSION_BIN=${BUNDLE_FUSION_PATH}/build/bundle_fusion_example

RUN git clone https://github.com/AnthonyDickson/BundleFusion_Ubuntu_Pangolin.git ${BUNDLE_FUSION_PATH} && \
    cd ${BUNDLE_FUSION_PATH} && \
    git checkout 2b9c1df && \
    mkdir build && \
    cd build && \
    cmake -DVISUALIZATION=OFF .. && \
    make -j8