name: video2mesh
channels:
  - conda-forge
dependencies:
  - absl-py=0.15.0
  - aiohttp=3.7.4.post0
  - aom=3.2.0
  - async-timeout=3.0.1
  - atk-1.0=2.36.0
  - attrs=21.2.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=35.0.0
  - cycler=0.10.0
  - cython=0.29.24
  - dataclasses=0.8
  - detectron2=0.5
  - expat=2.4.1
  - ffmpeg=4.4.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - fvcore=0.1.5.post20210804
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.3.2
  - google-auth-oauthlib=0.4.1
  - graphite2=1.3.13
  - graphviz=2.49.1
  - grpcio=1.41.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.0.0
  - hdf5=1.12.1
  - icu=68.2
  - idna=3.1
  - importlib-metadata=4.8.1
  - jasper=2.0.33
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.43.0
  - libopencv=4.5.3
  - libpng=1.6.37
  - libprotobuf=3.18.1
  - librsvg=2.52.3
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libvpx=1.11.0
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - multidict=5.2.0
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.21.3
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pango=1.48.10
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - portalocker=2.3.2
  - protobuf=3.18.1
  - psutil=5.8.0
  - py-opencv=4.5.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycocotools=2.0.2
  - pycparser=2.20
  - pydot=1.4.2
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.1
  - setuptools=58.2.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.36.0
  - svt-av1=0.8.7
  - tabulate=0.8.9
  - tbb=2021.4.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.8.0
  - termcolor=1.1.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - trimesh=3.9.34
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - werkzeug=2.0.1
  - wheel=0.37.0
  - x264=1!161.3030
  - x265=3.5
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.7.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - openmesh==1.1.6