name: video2mesh
channels:
  - conda-forge
dependencies:
  - aom=3.2.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - cffi=1.14.6
  - ffmpeg=4.4.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - grpcio=1.41.1
  - harfbuzz=3.0.0
  - hdf5=1.12.1
  - icu=68.2
  - jasper=2.0.33
  - jbig=2.1
  - jpeg=9d
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - libglib=2.70.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libopencv=4.5.3
  - libpng=1.6.37
  - libprotobuf=3.18.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libvpx=1.11.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.21.3
  - olefile=0.46
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.0
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - psutil=5.8.0
  - py-opencv=4.5.3
  - pycparser=2.20
  - python=3.8.12
  - python_abi=3.8
  - pytorch=1.10.0
  - pytorch-cpu=1.10.0
  - readline=8.1
  - scipy=1.7.1
  - setuptools=58.2.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.36.0
  - svt-av1=0.8.7
  - tk=8.6.11
  - torchvision=0.10.1
  - trimesh=3.9.35
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - x264=1!161.3030
  - x265=3.5
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==0.15.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - black==21.4b2
    - cachetools==4.2.4
    - certifi==2021.10.8
    - charset-normalizer==2.0.7
    - click==8.0.3
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - cython==0.29.24
    - detectron2==0.6
    - fvcore==0.1.5.post20211023
    - google-auth==2.3.2
    - google-auth-oauthlib==0.4.6
    - hydra-core==1.1.1
    - idna==3.3
    - importlib-resources==5.4.0
    - iopath==0.1.9
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - mypy-extensions==0.4.3
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - openmesh==1.1.6
    - pathspec==0.9.0
    - portalocker==2.3.2
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydot==1.4.2
    - pyparsing==3.0.4
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2021.10.23
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - toml==0.10.2
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - yacs==0.1.8
    - zipp==3.6.0
